DROP DATABASE IF EXISTS geeler;
CREATE DATABASE IF NOT EXISTS geeler;
USE geeler;

CREATE TABLE users(
  ID INT UNSIGNED NOT NULL PRIMARY KEY,
  username VARCHAR(25) NOT NULL UNIQUE,
  email VARCHAR(300) NOT NULL UNIQUE,
  joined TIMESTAMP(1) NOT NULL DEFAULT CURRENT_TIMESTAMP(1),
  INDEX index_users_username(username),
  INDEX index_users_email(email)
);
CREATE TABLE passwords(
  userFK INT UNSIGNED NOT NULL,
  password VARCHAR(256) NOT NULL,
  FOREIGN KEY (userFK) REFERENCES users(ID)
);
CREATE TABLE pagecontent(
  ID VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY,
  content TEXT NOT NULL,
  site VARCHAR(20) NOT NULL
);
