version: '3.8'
services:
   db:
      image: mariadb
      container_name: mariaDB
      ports:
         - '3306:3306'
      environment:
         MYSQL_ROOT_PASSWORD: 1234
      volumes:
         - dbdata:/var/lib/mysql
volumes:
   dbdata: